# Generated by Django 5.1.15 on 2026-09-27 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='标识')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('auth_type', models.CharField(choices=[('oauth2', 'OAuth 2.0'), ('mock', '演示'), ('api_key', 'API Key')], default='oauth2', max_length=32, verbose_name='认证方式')),
                ('authorize_url', models.CharField(blank=True, default='', max_length=255)),
                ('token_url', models.CharField(blank=True, default='', max_length=255)),
                ('api_base', models.CharField(blank=True, default='', max_length=255)),
                ('client_id', models.CharField(blank=True, default='', max_length=128)),
                ('client_secret', models.CharField(blank=True, default='', max_length=256)),
                ('scopes', models.JSONField(blank=True, default=list, verbose_name='授权范围')),
                ('capabilities', models.JSONField(blank=True, default=dict, verbose_name='能力（fetch/upload）')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '平台',
                'verbose_name_plural': '平台',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_user_id', models.CharField(max_length=128, verbose_name='平台侧用户 ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=128, verbose_name='显示名称')),
                ('access_token', models.TextField(blank=True, default='', help_text='Fernet 加密存储')),
                ('refresh_token', models.TextField(blank=True, default='', help_text='Fernet 加密存储')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已过期'), ('revoked', '已撤销')], default='active', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='platforms.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '平台账号',
                'verbose_name_plural': '平台账号',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'platform', 'platform_user_id'), name='uk_user_platform')],
            },
        ),
    ]
