# Generated by Django 5.1.15 on 2026-10-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='app_scheme',
            field=models.CharField(blank=True, default='', help_text='跳官方小程序不可用时的兜底：复制该 scheme 到系统浏览器即可唤起官方 App', max_length=128, verbose_name='官方 App URL Scheme'),
        ),
        migrations.AddField(
            model_name='platform',
            name='miniprogram_appid',
            field=models.CharField(blank=True, default='', help_text='小程序内用 wx.navigateToMiniProgram 跳转该平台官方小程序完成授权绑定', max_length=64, verbose_name='官方微信小程序 AppID'),
        ),
    ]
