# Generated by Django 5.1.15 on 2026-10-09 13:40

import apps.platforms.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_miniprogram_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='auth_type',
            field=models.CharField(choices=[('oauth2', 'OAuth 2.0'), ('mock', '演示')], default='oauth2', max_length=32, verbose_name='认证方式'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='client_secret',
            field=apps.platforms.fields.EncryptedTextField(blank=True, default=''),
        ),
    ]
