# Generated by Django 5.1.15 on 2026-09-27 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('wechat', '微信'), ('qq', 'QQ'), ('weibo', '微博')], max_length=32, verbose_name='平台')),
                ('openid', models.CharField(max_length=128, verbose_name='OpenID')),
                ('unionid', models.CharField(blank=True, default='', max_length=128, verbose_name='UnionID')),
                ('nickname', models.CharField(blank=True, default='', max_length=64, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, default='', verbose_name='头像')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='原始资料')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '第三方账号',
                'verbose_name_plural': '第三方账号',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'openid'), name='uk_social_provider_openid')],
            },
        ),
    ]
