# Generated by Django 5.1.15 on 2026-09-27 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='未命名活动', max_length=200, verbose_name='活动名称')),
                ('start_timestamp', models.DateTimeField(verbose_name='开始时间')),
                ('activity_type', models.CharField(blank=True, default='', max_length=32, verbose_name='运动类型')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('distance', models.FloatField(default=0, verbose_name='距离(km)')),
                ('source_platform', models.CharField(max_length=32, verbose_name='来源平台')),
                ('source_activity_id', models.CharField(blank=True, default='', max_length=128, verbose_name='来源平台活动 ID')),
                ('fit_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='FIT 文件哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['-start_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_activity_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('synced', '已同步'), ('pending', '待同步'), ('failed', '失败'), ('na', '不适用')], default='pending', max_length=16, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='同步时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_states', to='activities.activity')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platforms.platform')),
            ],
            options={
                'verbose_name': '活动同步状态',
                'verbose_name_plural': '活动同步状态',
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'start_timestamp'], name='idx_user_start'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['fit_hash'], name='idx_fit_hash'),
        ),
        migrations.AddConstraint(
            model_name='activitysyncstate',
            constraint=models.UniqueConstraint(fields=('activity', 'platform'), name='uk_activity_platform'),
        ),
    ]
