# Generated by Django 5.1.15 on 2026-10-07 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='文件名')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='文件 SHA256')),
                ('device', models.JSONField(blank=True, default=dict, verbose_name='设备信息')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='汇总指标')),
                ('samples', models.JSONField(blank=True, default=list, verbose_name='采样序列')),
                ('track', models.JSONField(blank=True, default=list, verbose_name='轨迹点')),
                ('parsed_at', models.DateTimeField(auto_now=True, verbose_name='解析时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fit_detail', to='activities.activity')),
            ],
            options={
                'verbose_name': 'FIT 解析详情',
                'verbose_name_plural': 'FIT 解析详情',
            },
        ),
    ]
