# Generated by Django 5.1.15 on 2026-09-27 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('auto_run', models.BooleanField(default=True, verbose_name='定时自动运行')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次运行')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '管道',
                'verbose_name_plural': '管道',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('source', '源'), ('filter', '过滤器'), ('target', '目标')], max_length=16, verbose_name='类型')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置（过滤器参数等）')),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, help_text='源/目标节点绑定的平台账号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_nodes', to='platforms.platformaccount')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='pipelines.pipeline')),
            ],
            options={
                'verbose_name': '管道节点',
                'verbose_name_plural': '管道节点',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PipelineEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='pipelines.pipeline')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='pipelines.pipelinenode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='pipelines.pipelinenode')),
            ],
            options={
                'verbose_name': '管道连线',
                'verbose_name_plural': '管道连线',
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待'), ('running', '运行中'), ('success', '成功'), ('partial', '部分成功'), ('error', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('nodes_state', models.JSONField(blank=True, default=dict, verbose_name='节点实时状态')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pipelines.pipeline')),
            ],
            options={
                'verbose_name': '管道运行记录',
                'verbose_name_plural': '管道运行记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
