# Generated by Django 5.1.15 on 2026-10-07 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activityfitdetail'),
        ('pipelines', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['-created_at'], 'verbose_name': '同步任务', 'verbose_name_plural': '同步任务'},
        ),
        migrations.AddField(
            model_name='pipeline',
            name='options',
            field=models.JSONField(blank=True, default=dict, verbose_name='同步选项'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='source_account',
            field=models.ForeignKey(blank=True, help_text='平台类来源绑定的账号；FIT 来源为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_tasks', to='platforms.platformaccount'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='source_fit_detail',
            field=models.ForeignKey(blank=True, help_text='指定某个已导入的 FIT 记录；为空表示该用户全部 FIT 记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_tasks', to='activities.activityfitdetail'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='source_type',
            field=models.CharField(choices=[('fit', 'FIT 文件 / 本地记录'), ('igpsport', 'iGPSPORT'), ('garmin', 'Garmin 佳明'), ('strava', 'Strava'), ('coros', 'COROS 高驰'), ('mock', '演示账号')], default='fit', max_length=32, verbose_name='数据来源'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='sync_content',
            field=models.JSONField(blank=True, default=list, verbose_name='同步内容'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='target_accounts',
            field=models.ManyToManyField(blank=True, related_name='target_tasks', to='platforms.platformaccount', verbose_name='目标账号'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='time_range',
            field=models.JSONField(blank=True, default=dict, verbose_name='时间范围'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='stats',
            field=models.JSONField(blank=True, default=dict, verbose_name='执行统计'),
        ),
    ]
